version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: redis
      MYSQL_ROOT_PASSWORD: redis
      MYSQL_USER: redis_example
      MYSQL_PASSWORD: redis
    platform: linux/x86_64
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
